spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      
#### 数据库连接池属性  datasource:    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/loser-thinking-scaffold?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    hikari:      auto-commit: true      maximum-pool-size: 100
      idle-timeout: 10
# mybatis对应的映射文件路径
mybatis:  mapper-locations:  - classpath:mappers/*.xml
  type-aliases-package: com.thinking.scaffold.model

    